### PR TITLE
New past tense methods

### PR DESCRIPTION
**Pull request by rricard**
Instead of push/pop/etc... be overridden, we keep them the same but create new methods in the past sense

### CODE REVIEW

**Comment by ljharb** [comment]
So would pop and push mutate? If not, they shouldn’t be present.

**Comment by rricard** [comment]
In the appendix the push is a no-op, and pop will return the last elem.

I do still want to keep them for now just in case we're able to possibly add pushed and popped and the others to Array.prototype.

**Comment by ljharb** [comment]
Why would push ever be a noop? Why would pop ever not pop the item - ie, remove it?

**Comment by rricard** [comment]
effectively having push as a no-op is not super useful. having pop as giving you the last element might actually end up being useful unless we add a .last()

**Comment by ljharb** [comment]
The name "pop" is destructive and mutates. It seems reasonable to advance `.last()` separately if that would be useful, but an immutable value should not have apparent mutator methods on it.

**Comment by rricard** [comment]
cc. @rickbutton let's have a chat about this this week

**Comment by papb** [comment]
If a method is a noop, I think it simply shouldn't exist instead. This would prevent bugs.

**Pull request merged**
