### PR TITLE
Add back Record.isRecord

### PR DESCRIPTION
**Pull request by littledan**
This was included before, and turns out to be needed in the context of #71

### CODE REVIEW

**Comment by littledan** [comment]
cc @ljharb

**Comment by Jack-Works** [comment]
Why not just typeof

**Comment by rricard** [comment]
typeof will detect the primitive type (record, tuple) but not the primitive type boxed into their boxing objects (Record, Tuple). It is an edge case but it could be useful to detect it.

**Comment by ljharb** [comment]
More specifically, it’s an axiom for every object value (except Error, for legacy reasons), including boxed primitives, that there must be a cross-realm mechanism to distinguish it.

**Pull request merged**
